/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import gui.Main;
import application.BriscolaStart;
public class App {
    private static boolean gui = true;
    /**
     * Starting the Application
     * @param args
     */
    public static void main(String[] args) {
        if (gui)
        {
            Main.main(args);
        }
        else
        {
            BriscolaStart.main(args);
        }
    }
}
